### ISSUE TITLE
pnpm detection not working properly

### ISSUE THREAD

**Issue by sprechblase** [skredev/docsframe#1]
### What happened? Describe the bug

Running the docsframe init command with pnpm dlx docsframe@latest init will still be recognised by the package as an npm package manager.

### What was the expected behavior

Recognize it as pnpm package manager

### Desktop or Smartphone?

Desktop

### OS?

Windows

**Comment by 0xkafkaa** [comment]
![Screenshot_2024-12-13_21-33-31](https://github.com/user-attachments/assets/f47124c2-962e-4c96-868a-5e8486c2db8a)
This is the issue you are mentioning right?

**Comment by sprechblase** [comment]
Yes, it looks like there's a problem with the way the pnpm command is being detected, which is causing it to default to the npm package manager when executed with pnpm
